<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BaseRepository.Application</RootNamespace>
    <AssemblyName>BaseRepository.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\BaseRepository.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

</Project>
